# Generated by Django 4.2.12 on 2025-12-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('supplier_type', models.CharField(choices=[('mopar', 'Mopar'), ('aftermarket', 'Aftermarket'), ('other', 'Other')], default='mopar', max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('default_terms', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
