# Generated by Django 4.2.12 on 2025-12-06 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting_refund', 'Waiting on refund'), ('refunded', 'Refunded'), ('denied', 'Denied')], default='waiting_refund', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('rma_number', models.CharField(blank=True, max_length=128)),
                ('refund_received_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='invoices.invoiceline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
